image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: pyenv versions                                                           &&
          pip3 install --upgrade pip                                               &&
          pip3 install tensorflowjs                                                &&
          pip3 install netron    "dask[delayed]"                                   &&
          chmod +x a01-convert-tfjs-arduino.sh                                     &&       
          tflite_convert --help                                                    &&
          tensorflowjs_converter --help                                            &&
          xxd --help                                                               &&
          echo "upload your model.json and model.weights.bin files here then run ./a01-convert-tfjs-arduino.sh"                                                                                                                          

              
